apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: valhalla
  name: valhalla
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: valhalla
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valhalla
    spec:
      containers:
      - image: minus34/valhalla:latest
        name: valhalla
        ports:
        - containerPort: 8002